### ISSUE TITLE
Error when adding section after enabling config via project.yaml

### ISSUE THREAD

**Issue by andersaloof** [engram-design/SuperTable#245]
### Description

Adding a new section after upgrading to using project.yam in a project, results in the following error.

"Unable to save a Super Table field’s settings without knowing its content table:"

### Steps to reproduce

1. Dump production database (a project without project.yaml, craft 3.1.8)
2. Import database locally
3. Go to admin and run database upgrades from 3.1.8 to 3.1.12
4. Login to dashboard
5. Enable project.yaml in general.php and reload dashboard
6. Add new single section and get error upon saving

### Additional info

The stangeness in this, is that if I do the following, it works:
1. Dump production database (a project without project.yaml, craft 3.1.8)
2. Import database locally
3. Enable project.yaml in general.php
4. Go to admin and run database upgrades from 3.1.8 to 3.1.12 (project.yaml will be generated at the same time)
5. Add new single section and it works as expected

I've diffed the two project.yaml filed generated from each approach, and the only diff between them is the timestamp. 

I've tried to debug the code, finding out why contentTable is not set. Project.yaml lists 5 fields, all Super Table fields with `contentTable: null`, but if I check the database table **fields**, the contentTable is correctly specified in the settings column for all 5 fields.

However, it looks to me as the project.yaml file is created from the **info.config** serialized object, and within this object, the same 5 fields has not a defined contentTable.

- Plugin version: 2.1.8
- Craft version: 3.1.12

**Comment by engram-design** [comment]
Quick question, have you tried running the content-checker function https://github.com/verbb/super-table#craft-31-changes ?

**Comment by nettum** [comment]
I can also confirm that my supertable-fields inside `project.yaml` is missing contentTable values (tested on two different project that has been updated from 3.0 -> 3.1).

I did the following on an updated craft 3.1 project:
1) Delete `project.yaml` just to be sure to generate a new one.
2) Reload admin to generate new project.yaml (no changes).
3) Check a random supertable-field in DB:
`SELECT settings FROM fields where uid = '0c448f3f-3742-4aef-9572-c7cda5dbc2cf';`
```
{
  "minRows": "",
  "maxRows": "",
  "localizeBlocks": "",
  "staticField": "",
  "columns": {
    "20": { "width": "" },
    "21": { "width": "" },
    "22": { "width": "" }
  },
  "contentTable": "{{%stc_4_linkedpages}}",
  "fieldLayout": "row",
  "selectionLabel": "Legg til flere rader"
}
```
4) Looking up settings for the same field in `project.yaml`:
```
        settings:
          columns:
            20:
              width: ''
            21:
              width: ''
            22:
              width: ''
          contentTable: null
          fieldLayout: row
          localizeBlocks: ''
          maxRows: ''
          minRows: ''
          selectionLabel: 'Legg til flere rader'
          staticField: ''
```

`/actions/super-table/plugin/check-content-tables` says "No errors found".
Craft 3.1.12, Super Table 2.1.8
