### ISSUE TITLE
Column Width settings don't properly sync from the project config file

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/SuperTable#309]
### Description
We're using a Super Table field with the **Table Layout** option. With this option, you can define the **Column Width** for various sections. The column widths display properly when initially set up, but after syncing from the project config, the **Column Width** options seem to apply to the incorrect fields.

Initially, I simply enabled `allowAdminChanges` on staging to quickly fix up the improperly synced column widths, but future project config syncs broke it again.

### Section from our project.yaml file

```
dbfbd275-5762-4f88-83e7-dd208abc3426:
  name: 'Menu Items'
  handle: inStoreMenuItems
  instructions: "Items for the in-store menus."
  searchable: true
  translationMethod: site
  translationKeyFormat: null
  type: verbb\supertable\fields\SuperTableField
  settings:
    minRows: ''
    maxRows: ''
    contentTable: '{{%stc_instoremenuitems}}'
    propagationMethod: all
    staticField: ''
    columns:
      243:
        width: 150px
      246:
        width: ''
      245:
        width: ''
      248:
        width: 65px
      249:
        width: 65px
      247:
        width: 65px
      244:
        width: 65px
    fieldLayout: table
    selectionLabel: 'Add an item'
  contentColumnType: string
  fieldGroup: 0e5a08f3-82fe-4970-ae57-0bc4c06c4b25
```

### Example of our field after initial setup
![table-layout-good](https://user-images.githubusercontent.com/1007191/67523333-559c1b80-f663-11e9-9297-0cdda35e6d09.png)

### Example of our field after a project config sync
![table-layout-bad](https://user-images.githubusercontent.com/1007191/67523349-5cc32980-f663-11e9-945a-4dbbdf53f1cf.png)

### Additional info

- Plugin version: 2.3.0
- Craft version: 3.3.13
