### ISSUE TITLE
Matrix view column/field width

### ISSUE THREAD

**Issue by WHITE-developer** [engram-design/SuperTable#499]
### What are you trying to do?

I would love to see some way to get the matrix view more like the default matrix width options.
I see it was added here https://github.com/verbb/super-table/pull/422.
But later on removed here https://github.com/verbb/super-table/commit/fd6fc1f58153bd5f2a6a878464adf96ed8b8df13.

### What's your proposed solution?

I get it isn't the prettiest way, but maybe bring it back?
To make it more mobile friendly maybe just add some additional CSS to force it to 100% width again on mobile like Craft does on the 600px breakpoint?
```css
@media only screen and (max-width: 599px) {
    .superTableMatrix.matrixblock .field {
        width: 100% !important!
    }
}
```
